### ISSUE TITLE
Not working for .tsx or .jsx files

### ISSUE THREAD

**Issue by eedrxs** [moalamri/vscode-inline-fold#10]
The extension doesn't seem to work for non .html files. Even when I edited the regex used in matching and added ".tsx"/".jsx" to the list of files it handles from its setting, it still doesn't work.

**Comment by ali-issa** [comment]
You should add `javascriptreact` and `typescriptreact` to the list of supported languages in the plugin settings. Alternatively, you can add this to your VS Code JSON settings file:

```
 "inlineFold.supportedLanguages": [
    "javascript",
    "typescript",
    "javascriptreact",
    "typescriptreact",
    "html"
  ],
```

**Comment by eedrxs** [comment]
Okay then, that's great.

But the documentation of the extension really needs lots of improvement as it currently doesn't make it easy to understand how to use it. I can help with that if you'd be open to collaborate.

**Comment by moalamri** [comment]
> Okay then, that's great.
> 
> 
> 
> But the documentation of the extension really needs lots of improvement as it currently doesn't make it easy to understand how to use it. I can help with that if you'd be open to collaborate.

You are absolutely right, the documents needs some work, examples and use cases.. etc
Yes please I would appreciate any contribution.

**Comment by eedrxs** [comment]
> > Okay then, that's great.
> > But the documentation of the extension really needs lots of improvement as it currently doesn't make it easy to understand how to use it. I can help with that if you'd be open to collaborate.
> 
> You are absolutely right, the documents needs some work, examples and use cases.. etc
> 
> Yes please I would appreciate any contribution, but it would be better to present the extension as general use case. Not limited to a language or a framework :basecampy:
> 
> Thank you in advance

Okay, then. Lemme get to work. Happy to collaborate 🤝

**Comment by moalamri** [comment]
Mr @ali-issa has made some changes to the readme.md file.
You might want to start with the new changes 👍

**Comment by ali-issa** [comment]
@eedrxs @moalamri Including [this](https://code.visualstudio.com/docs/languages/identifiers) in the documentation will help people find the right identifiers for the languages they're using.

**Comment by moalamri** [comment]
@ali-issa 👯‍♂️
