### ISSUE TITLE
Inline folds unfold automatically when passing over a folded section

### ISSUE THREAD

**Issue by 0x-j** [moalamri/vscode-inline-fold#100]
I noticed this recently. I normally like to fold my headers after I am done working on them to save space. I noticed when using VScode Vim, that when moving upward, past a folded section (header in this case), the inline folds will still work, but only above the folded region. Everything below the folded region automatically unfolds out of their inline folds. This may have something to do with VScode Vim's settings interacting with Inline Fold, or it may just be VScode's own section folding. I do have the VScode Vim setting "Vim:Foldfix" toggled on (which allows VScode Vim to maneuver around folds properly). I'm not sure what is causing this behavior, but I thought I'd bring it to your attention, seeing as many people are using and depend on this plugin to make their workflow easier. Thank you for all your hard work on this plugin. It really has made working with TailwindCSS much more palatable and intuitive.

**Comment by moalamri** [comment]
Hey @0x-j 
I strongly believe that this is because of the optimization that is done to the extension in its second release (only the visible area of code will be processed for folding, unfolding) perhaps in vim mode the visible range is somehow updated differently. or could be possibly related to this [bug](https://github.com/microsoft/vscode/issues/154977). 
Thanks for the report, I will look into it soon.

**Comment by moalamri** [comment]
Thanks to @Zer0xTJ He was able to spot the issue, it was indeed related to `Vim:Foldfix`.

**Comment by moalamri** [comment]
After investigating, it is totally from VSCode & Vim extension side, as it manually changes the [cursor position](https://github.com/VSCodeVim/Vim/blob/2508ed8f115a49b1dc5285bbf99355dd7294ed33/src/actions/motion.ts#L344) which confuses inline-fold extension. It can be solved if VSCode adds an [API to check for the folding state of the active position](https://github.com/Microsoft/vscode/issues/22276), then Vim could use that API to determine the state without changing the position.

The only solution for now is to disable `Foldfix`.
Closing this for now 👍🏻

**Comment by 0x-j** [comment]
I'll go forward this issue to VScode and VSCode Vim and see if they have time to add that API. We'll see if they both think this is relevant. I think the more prominent Tailwind CSS becomes, the more likely they'll be to come around to it.

**Comment by moalamri** [comment]
> I'll go forward this issue to VScode and VSCode Vim and see if they have time to add that API. We'll see if they both think this is relevant. I think the more prominent Tailwind CSS becomes, the more likely they'll be to come around to it.

I don't think that is possible, see Jrieken response [here](https://github.com/Microsoft/vscode/issues/22276#issuecomment-345259409) (which is more than 4 years ago).
VSCode Vim can't do much without that suggested API.
