### ISSUE TITLE
Add toggle command to `Clear cache` and `Toggle fold state` at once

### ISSUE THREAD

**Issue by moalamri** [moalamri/vscode-inline-fold#102]
If I use `Inline Fold: Toggle` in VSCode Command Palette, it works fine (i.e. unfolds) on the current file. If I open another file, it goes back to folding everything...

As a feature request, I think the behavior of that `Toggle` action should be permanent. In lieu of that, introduce two new actions like:

- `Inline Fold: Disable until I turn it back on`
- `Inline Fold: Enable until I turn it off

_Originally posted by @corysimmons in https://github.com/moalamri/vscode-inline-fold/discussions/101_

**Comment by moalamri** [comment]
@0f1

**Comment by moalamri** [comment]
@0f1 the first solution is working, but it take you back again to per file folding state.
So I added an option to opt out from per file folding.
That way we don't have to register a command & it won't break anything since the default option is `true`.

@corysimmons in order to fit your use case you can use the latest update v0.2.3 and set the option `inlineFold.togglePerFile: false` to opt out from the default toggle action (per file).

**Comment by corysimmons** [comment]
Amazing! Thank both of you so much for the great maintenance of this very helpful extension! I'll check back in if it doesn't work.
