### ISSUE TITLE
Incorrect folding

### ISSUE THREAD

**Issue by cycle4passion** [moalamri/vscode-inline-fold#105]
My use case is Tailwind in Svelte. In Svelte you do not need to use backticks and ${} just {}

```js
 <div class="{bullet?.break ? '-mt-2' : ''}" >
```

becomes

```js
<div class=". . . }"
```

If I used more standard backticks and string interpolation

```js
<div class=`${bullet?.break ? '-mt-2' : ''}`>
```

It also becomes

```js
<div class=". . . }"
```

**Comment by moalamri** [comment]
Hey @cycle4passion 
Here's my working Svelte settings:
```json
"inlineFold.regex": "class=\"(.*?)\""
"inlineFold.regexGroup": "1"
```
It will work perfectly with whatever between quote marks 👍🏻 
Although I tend to use Svelte's directives in such case, your code would be 
```js
class:-mt-2={bullet?.break}
```
That's why I like Svelte 😃

**Comment by cycle4passion** [comment]
awesome
