### ISSUE TITLE
Unfolded classes w/dimmed text

### ISSUE THREAD

**Issue by cycle4passion** [moalamri/vscode-inline-fold#106]
unfolded classes that haven been touched thereafter appear dimmed, and shouldn't be. In the image, I had previously updated the second div class.

<img width="624" alt="Screenshot 2023-02-19 at 8 23 40 AM" src="https://user-images.githubusercontent.com/6192217/219950953-0bad73ab-c3e3-4177-8e30-802341040707.png">

**Comment by moalamri** [comment]
Use `"inlineFold.unfoldedOpacity": 1` to disable dimming, it's set to `0.7` as default
