### ISSUE TITLE
Add support for Clojure/hiccup out of the box

### ISSUE THREAD

**Issue by leandrowilliam** [moalamri/vscode-inline-fold#109]
Hello, I have configured the extension locally to provide support for Clojure. How can I add it out of the box?

**Comment by leandrowilliam** [comment]
After reviewing the extension's code, I have not found support for adding regex based on the language type. What steps should be taken to enable this feature?

**Comment by leandrowilliam** [comment]
Is there something I can do to help?

**Comment by moalamri** [comment]
> Hello, I have configured the extension locally to provide support for Clojure. How can I add it out of the box?

https://github.com/moalamri/vscode-inline-fold/blob/c9cfe599be4b668f03f929162410232991623261/package.json#L67


> After reviewing the extension's code, I have not found support for adding regex based on the language type. What steps should be taken to enable this feature?

Please review the [documentation ](https://github.com/moalamri/vscode-inline-fold) there are examples on how to make language-specific settings
