### ISSUE TITLE
Inline Fold should be disabled when viewing file diff in diff editor

### ISSUE THREAD

**Issue by babakfp** [moalamri/vscode-inline-fold#116]
![Screenshot 2023-06-14 051528](https://github.com/moalamri/vscode-inline-fold/assets/44144724/6553085d-d2fe-4f68-9edb-6a9363c9ec16)

**Comment by moalamri** [comment]
Hey @babakfp 
Thanks for the suggestion, I didn't notice it since I use diff in single view. I will look into a way or if there's an available API to detect the editor type to disable the extension and perhaps add an option to enable this behavior (to have the extension working in diff view)
