### ISSUE TITLE
Don't fold when line is selected

### ISSUE THREAD

**Issue by MrFoxPro** [moalamri/vscode-inline-fold#119]
https://github.com/moalamri/vscode-inline-fold/assets/17229619/f0629ffa-d89d-4166-b01f-32f42e767d9e

**Comment by moalamri** [comment]
Hey @MrFoxPro 
I was able to reproduce this and it only happens when I don't select from the start of the - suppose to be - folded text. I will assume it is something to deal with active selection range.
Thanks for reporting.

**Comment by babakfp** [comment]
A similar issue:

https://github.com/moalamri/vscode-inline-fold/assets/44144724/c87bbb39-703a-4ce4-a608-0d9bd7d07ea4
