### ISSUE TITLE
Not working on .js or .jsx files

### ISSUE THREAD

**Issue by trevorwrightdev** [moalamri/vscode-inline-fold#12]
Can someone tell me how to get this working on js and jsx files? Also ts and tsx files? It doesn't seem to be working sadly. It seems like a really cool extension so if you could tell me how to get it running that would be great.

**Comment by ali-issa** [comment]
You should add `javascriptreact` and `typescriptreact` to the list of supported languages in the plugin settings. Alternatively, you can add this to your VS Code JSON settings file:

```
 "inlineFold.supportedLanguages": [
    "javascript",
    "typescript",
    "javascriptreact",
    "typescriptreact",
    "html"
  ],
```

**Comment by ali-issa** [comment]
Check my answer at #10

**Comment by trevorwrightdev** [comment]
> Check my answer at #10

Is this all I need to do? Because I think I did it and it still does not work. My supported languages looks like this: 
<img width="438" alt="image" src="https://user-images.githubusercontent.com/86077703/177474832-1740cd42-b3c4-427c-8c9e-f022feb86eb2.png">
I also changed this regex from class to className like this: 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/86077703/177474924-bc9c3378-b0b0-4380-9d87-30349860f17c.png">
Do I need to do anything else? Keeping className as class also does not work.

**Comment by ali-issa** [comment]
Try this regex `className="(.*?)"`. Make sure to click outside the input field before leaving the settings page, so that the settings will be applied.

**Comment by moalamri** [comment]
I'm pushing an update today to support react out of the box

**Comment by moalamri** [comment]
Please update the extension and restart VS Code then reset the `regex` and `regexGroup` settings to the default values.
