### ISSUE TITLE
Folded line is not collapsed to a single line

### ISSUE THREAD

**Issue by pinkfrog9** [moalamri/vscode-inline-fold#120]
<img width="1284" alt="image" src="https://github.com/moalamri/vscode-inline-fold/assets/107285219/357184f3-eb41-4e45-be30-a3a16204ae87">
The above is folded into: 
<img width="533" alt="image" src="https://github.com/moalamri/vscode-inline-fold/assets/107285219/2db56edc-f32f-4583-aa01-695b1b80cb68">

Notice the blank line in the <path> tag.

**Comment by moalamri** [comment]
Hey
This explains the issue.
https://github.com/moalamri/vscode-inline-fold/discussions/69#discussioncomment-4150206

**Comment by pinkfrog9** [comment]
Thanks @moalamri !
