### ISSUE TITLE
Classes not folding when using template literals

### ISSUE THREAD

**Issue by vinibortoletto** [moalamri/vscode-inline-fold#121]
Hi! Is there a way to configure Inline Fold to also fold template literals? 

![image](https://github.com/moalamri/vscode-inline-fold/assets/47364504/c97fde55-50d9-4d9a-9e5d-237e0bdbadc3)

**Comment by moalamri** [comment]
I believe it can be done by tweaking the regex. @e-medeiros is it possible?

**Comment by e-medeiros** [comment]
@vinibortoletto @moalamri sure can be... When I got some free time I can try to create a reges for this.

**Comment by vinibortoletto** [comment]
@e-medeiros Personally, I'd prefer to keep everything hidden and only see "...", I find it keeps the code cleaner and more readable, but both ways are nice.

Here are some cases where the classes won't fold (I'm using Vue.js, don't know if it makes any difference):

```vue
<button
   :type="type"
   :id="id"
   :class="`disabled:border-0 disabled:bg-slate-300 disabled:text-slate-500
      p-2 font-bold transition rounded w-40 mx-auto ${styles}`"
   :disabled="disabled"
>
   {{ text }}
</button>
```

With ternary operator:

```vue
<span
   :class="`absolute left-0 bg-white border p-6 max-w-sm rounded shadow-lg transition-all
      ${isUrlModalOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'}`"
>
   {{ url }}
</span>
```

With function:

```vue
<div
   :class="`p-2 w-fit font-bold transition rounded mx-auto text-center ${getStyles(param)}`"
>
   {{ param }}
</div>
```

Only template literals and no variables:
```vue
 <input
      type="text"
      :value="param.key"
      :id="paramValue"
      :class="`p-2 border rounded bg-slate-100 focus:outline-none
      focus:border-sky-500 focus:ring-sky-500 focus:ring-1 disabled:bg-slate-300 
      disabled:text-slate-500 border-slate-400`"
      @input="() => {}"
      @keydown="disableWhitespace"
/>
```

Interesting that in this case, it folds:

```vue
<AppInventoryButton
      :isInventoryOpen="false"
      @click="toggleInventory"
      :class="`${isInventoryOpen ? hiddenStyles : visibleStyles}`"
/>
```
![image](https://github.com/moalamri/vscode-inline-fold/assets/47364504/64ca697d-69ad-4ba8-ba07-47c29e97e825)

**Comment by e-medeiros** [comment]
```json
  "inlineFold.regex":"(class)=(['\\\"`])((.|\\s)*?)(\\2)",
  "inlineFold.regexGroup": "3",
```
try this regex options. may do the trick.
the last one folding but sometimes not like the way I wanted... maybe in near future I update it

**Comment by vinibortoletto** [comment]
@e-medeiros That worked! Thanks for the help! 

![image](https://github.com/moalamri/vscode-inline-fold/assets/47364504/1e43a074-7cba-4c41-bc5c-eb6b0dd29245)
