### ISSUE TITLE
This lags the entire editor and wont let me save or delete stuff, also lags git out.

### ISSUE THREAD

**Issue by surajmandalcell** [moalamri/vscode-inline-fold#123]
Type: <b>Bug</b>

Issue pretty much summed up in the title.

Extension version: 0.2.4
VS Code version: Code - Insiders 1.83.0-insider (Universal) (03671d332bf6a34782d5adc64086bc8e083a1590, 2023-09-12T15:08:34.081Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 9, 8|
|Memory (System)|8.00GB (0.60GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by moalamri** [comment]
Hey @surajmandalcell 
Could you please provide more info, like the regex, because a misconfigured regex could definitely lag the editor

**Comment by surajmandalcell** [comment]
I removed the extension but here is what my regex was, maybe this was the issue.
```json
"inlineFold.regex": "^(?!.)",
```

**Comment by e-medeiros** [comment]
@surajmandalcell  

Try this config 
```json
  "inlineFold.regex":"(class)=(['\\\"`])((.|\\s)*?)(\\2)",
  "inlineFold.regexGroup": "3",
```

**Comment by moalamri** [comment]
> I removed the extension but here is what my regex was, maybe this was the issue.
> 
> ```json
> "inlineFold.regex": "^(?!.)",
> ```

Yes the regex is incorrect, if I correctly understand it, it start with `^` which means it must be at the beginning of line, then followed by a capture group that starts with `?!` which means ignore the following and look after that, then you added `.` which means match all characters until the end of the current line, while all characters are ignored by the `?!`. 
That’s definitely a misconfigured regex.
Please use @e-medeiros suggested settings.

**Comment by surajmandalcell** [comment]
I've disabled the extension since I don't use it anyhow. The thing is that I don't remember changing anything related to regex in setting specially for inline fold 🤷
