### ISSUE TITLE
Turn the folding ON/OFF with hotkey

### ISSUE THREAD

**Issue by jsandlerus** [moalamri/vscode-inline-fold#124]
Hi, I love the idea. I use it to have a clean code, but when I have to code I need to see the styling of multiple elements simultaneously. Hovering over each of them each time does not make it useful.

Would it be possible to add a keyboard hotkey where I can turn on/off all the folding for the current document at once?
Example: I press the hotkey and everything unfolds, releasing the key folds everything again.

I haven't been able to find a workaround for this yet, other than disabling the whole extension

**Comment by moalamri** [comment]
already mentioned in #67
