### ISSUE TITLE
Enabling Disabling 

### ISSUE THREAD

**Issue by adiadds** [moalamri/vscode-inline-fold#127]
I love the plugin. Could you please consider adding a shortcut to enable and disable it? While writing CSS, we often need to keep an eye on the entire CSS code. However, when we're writing logic in any programming language, we don't require the CSS code to be visible. Having a shortcut to enable or disable the plugin would greatly enhance the coding experience for developers.

**Comment by moalamri** [comment]
Hey @adiadds 
There are already a registered commands one of them is to disable/enable the extension, please refer to 
https://github.com/moalamri/vscode-inline-fold#keyboard-shortcuts
