### ISSUE TITLE
[bug] Fails to properly fold some classes if there is a folded code block in a file

### ISSUE THREAD

**Issue by DanikVitek** [moalamri/vscode-inline-fold#129]
https://github.com/moalamri/vscode-inline-fold/assets/25585136/aeffcfd4-c8de-4091-8207-b7df3b2a0690

**Comment by babakfp** [comment]
I use this config:

```json
{
    "inlineFold.regex": "(class)=\"(.*?)\"",
    "inlineFold.regexGroup": "2",
}
```

I'm not sure, but I think if you change `"(class)=\"(.*?)\""` to `"(class|className)=\"(.*?)\""`, then it will work for `className` too.
