### ISSUE TITLE
Inline fold is causing infinite loading of `Loading IntelliSense status` when regex is complex?

### ISSUE THREAD

**Issue by Norlandz** [moalamri/vscode-inline-fold#130]
### situation & problem

Just happened today, when I was coding. I found that the IntelliSense stopped working & the indicator shows the language IntelliSense keeps loading infinitely.

I tried to turn off my extensions one by one & finally found Inline fold is causing it. 

![image](https://github.com/moalamri/vscode-inline-fold/assets/43581880/816d1cb3-d624-4273-a596-48504cbbbe74)

### suspecting cause 

- this regex `(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,})??` causes problem, though its valid; 
  if I change to something simple `(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,})`, problem fixed 
- too complex & heavy load performance problem?
- <strike>bug happens when the regex group has no match? //dont_think_so</strike>

### environment

Inline Fold v0.2.6
Vscode Version: 1.84.2 (user setup)

### setting 
```json
  "inlineFold.regexGroup": "1",
  "inlineFold.regex": "(?<=^ *\\/\\/)(?: @.*?: )?(?<main>.{200,})??",
  "inlineFold.regexFlags": "gm",
  "inlineFold.supportedLanguages": [
    // "astro",
    // "vue",
    // "html",
    // "svelte",
    // "vue-html",
    // "php",
    // "blade",
    // "erb",
    // "twig",
    // "nunjucks",
    // "django-html",
    // "jinja-html",
    "javascript",
    "typescript",
    "javascriptreact",
    "typescriptreact",
    // "json"
  ],
```
![image](https://github.com/moalamri/vscode-inline-fold/assets/43581880/62557922-c2b1-44ed-908c-24d7bc84727c)

**Comment by moalamri** [comment]
Hey @Norlandz 
Thanks for the detailed explanation.
I will have a look on this very soon

**Comment by emedeirox** [comment]
I remember when greedy regex is used it can lead to performance issues... (correct me if i'm wrong)... tried to replicate with no sucesss....
maybe this work?
```regex
(?<=^ *?\/\/)(?: @.*?: )?(?<main>.{200,})??
```

**Comment by emedeirox** [comment]
@Norlandz what is the regex for? Just curious 👀

**Comment by Norlandz** [comment]
@emedeirox 

### example usage
```
(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,})?
```
```
  // some simple comment, dont fold this
  // @fixthis[due to some problem]: dont fold this, cuz this is not long enough, blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla
  // @fixthis[due to some problem]: fold things after this point, cuz this is a very long sentence, blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla
  // fold things after this point, cuz this is a very long sentence, blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla
```

### about `??` lazy match or not 
```
(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,}) -- this works most of the time 
(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,})? -- this works sometimes
(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,})?? -- this breaks (though I shouldnt use it, cuz it actually doesnt produce the match I want.)
^ *\/\/.{25}(.{200,}) -- for performance, this is what Im currently using 
```
- I actually should not use the lazy version `(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,})??`, it **doesnt produce** the match I want.
  **though**, still, the regex is valid, its shouldnt cause the infinite loading
- I think its some performance issue, dont think its related to lazy or not 

### for unable to reproduce

Maybe try to create a medium size project with like 20 files. 
And some of the file contains some extremely long comment lines -- about **4000 characters** (though this is long for human, this is shouldnt be long for regex)

Pay attention to the `Loading IntelliSense status` icon, should start keeps **spinning**, once you **change the setting** of the regex / or even after you reload vscode.

**Comment by Norlandz** [comment]
@moalamri  (Dont waste too much time on this yet. Now I have a feeling maybe its not inline fold's issue. I will keep an eye on vscode.)

**Comment by Norlandz** [comment]
@moalamri  @emedeirox 

So, I have been trying to disable & enable extensions **on and off** for last days.

### In short

Inline fold is **not** the main/only cause.
Its Typescript & Vscode intellisense.

### Details

#### **main cause** -- Vscode & Typescript
- - Vscode 1.84.2
  - **Typescript 5.2.2 + tsconfig.json**
  - (without Inline fold)
  - (with very few extensions (~6), tried different group/combination of extensions)

- -> **Occasionally** makes **infinite loading of `Loading IntelliSense status`**;
  Happens in the midway when you are writing code.
- This is the **main cause**.
- No way to fix it, but just restart Vscode when it happens... (tried search online, no help)
  - Or maybe tune the `tsconfig.ts` 
  - Or wait for a better Typescript version / Vscode intellisense version & hope its fixed

#### minor cause -- Inline fold & some weird regex
- - Vscode 1.84.2 
  - Inline fold v0.2.6 
  - regex `(?<=^ *\/\/)(?: @.*?: )?(?<main>.{200,})??` 
  - (without any other extension)
  - (does project structure contribute to this? havent test)

- -> **Always** (right after you set the weird regex / even reload) makes infinite loading of `Loading IntelliSense status`
- To fix it, just **dont use the weird regex**.

### Other que

#### This is unlikely to be caused by other extensions

- For 

  - Codeium
  - IntelliCode - Microsoft 
  - Eslint 
  - some refactor extensions
  - some code highlight/visualization enhance extensions

  they are **unlikely** the cause.

- Because I tried to disable some of them, but the problem just comes back & back again, **no matter** they present or not.

  (Of couse I didnt disable & enable only one extension one by one, (I dont have the time for that); 
  I disable a **group/combination** of them, chosen kinda randomly, to exclude a group of potential cause)

### Misc

- This happened after a **recent update** of Vscode, not before.

- I am closing this since this is **not** mainly caused by inline fold.
  If you want to reopen this, feel free to do so.
