### ISSUE TITLE
[BUG] - Folding more than class or className

### ISSUE THREAD

**Issue by roberto-saliola** [moalamri/vscode-inline-fold#131]
Hi,

I noticed a bug that I don't think is already discovered. In the images below you can see that the extension is also folding content after the className

Without folding: 
<img width="942" alt="image" src="https://github.com/moalamri/vscode-inline-fold/assets/119404837/269c9199-88d7-44dd-aa2e-f66635e2fd3e">

With folding:
<img width="450" alt="image" src="https://github.com/moalamri/vscode-inline-fold/assets/119404837/24902c40-d7a9-46f6-8c2f-ec21b8f1e9ea">

**Comment by emedeirox** [comment]
Its seens a misbehaviour of regex...
Please provide the settings you are using so we can replicate it.

**Comment by ctf0** [comment]
u can try this regex instead `"inlineFold.regex": "(?<=(class|className|style|xmlns|[^\\w]d)=\")(.*?)(?=\")",`
