### ISSUE TITLE
[BUG] typo in documentation's SVG section and empty lines when SVG is hidden

### ISSUE THREAD

**Issue by j-grosse** [moalamri/vscode-inline-fold#133]
## Screenhot
![by default 2024-01-13 at 08 47 18](https://github.com/moalamri/vscode-inline-fold/assets/103175813/a7a0b8ca-1498-4d2a-8c56-feac5af3f8ec)

### not hidden
![by default 2024-01-13 at 09 12 05](https://github.com/moalamri/vscode-inline-fold/assets/103175813/75041088-084c-4db0-82a4-4571221b45f4)
### hidden
![by default 2024-01-13 at 08 55 42](https://github.com/moalamri/vscode-inline-fold/assets/103175813/db9286b8-9a34-41a0-a875-7f739c80515b)

**Comment by emedeirox** [comment]
See #69 for further information.
