### ISSUE TITLE
Overflow ellipsis style folding

### ISSUE THREAD

**Issue by gar1t** [moalamri/vscode-inline-fold#135]
I would love to use this extension but I need to be able to see the CSS without having to move the cursor. I realize this request is a deviation from the current design, to the point it's not even "folding" anymore. But I'd love to be able to see up to N chars or chars up to an Nth terminal position, followed by a fold symbol (e.g. ellipsis). This would be similar to to the way overflow text is rendered with an ellipsis. The idea is you get to see as much of the value as you can with the rest truncated.

This is just an idea.

**Comment by moalamri** [comment]
Please refer to the repository README
