### ISSUE TITLE
Inline Fold should be disabled when viewing file diff in diff editor

### ISSUE THREAD

**Issue by babakfp** [moalamri/vscode-inline-fold#136]
Hi

https://github.com/moalamri/vscode-inline-fold/issues/116

Has something changed and caused this to break?

https://github.com/moalamri/vscode-inline-fold/assets/44144724/7ff59272-365f-4b85-a883-6ea178526c4f

**Comment by moalamri** [comment]
It seems like an update from VS Code has broke something, unfortunately I won't be able to work on it, please refer to [132](https://github.com/moalamri/vscode-inline-fold/discussions/132)
