### ISSUE TITLE
support more styling options

### ISSUE THREAD

**Issue by ctf0** [moalamri/vscode-inline-fold#137]
atm we only have support for text color https://github.com/moalamri/vscode-inline-fold/blob/9097ee147f57117482b1d11d3cbe7b6818636eb8/src/decoration.ts#L34

but it would be awesome if we could have support for all of css features instead.

**Comment by moalamri** [comment]
It was in my backlog to add more customization, but this extension is dead as discussed in [132](https://github.com/moalamri/vscode-inline-fold/discussions/132)
