### ISSUE TITLE
Reveal classes on hover on masked chars

### ISSUE THREAD

**Issue by androizer** [moalamri/vscode-inline-fold#16]
Hi,

I like the extension alot and it saves alot of space on the editor. Thanks for such a great extension @moalamri. 

I think hovering on the masked chars revealing all the classes inside a popover can be a great feature to have. This will help us with some few extra clicks.

Moreover, conditional masking can be applied on the basis of number of classes crossing certain threshold.

This scenario won't hurt since only 2 classes are used.
```html
<div className="rounded p-4"></div>
```

But this would be great scenario of masking.
```html
<button className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"></button>
```

Hope you also find these feature helpful.

Thanks.

**Comment by androizer** [comment]
Hey @moalamri,
Thanks for the clarification on the first suggestion.
Regarding the second one, here is the default regex `(class|className)=[`'{"]([^`'"}]*)[`'"}]`. Can you help me in modifying it bit according to the above case you mentioned. Just wanted to know how this works.

Thanks.

**Comment by moalamri** [comment]
Hey @androizer 
Could you try the following:
`(class|className)=['{"]([^'"}]{10,120})['"}]`

**Comment by GBrachetta** [comment]
I would also like to see this properly configurable in the extension settings. Something like "Fold when there's a minimum of N classes"/

**Comment by androizer** [comment]
> Hey @androizer Could you try the following: `(class|className)=['{"]([^'"}]{10,120})['"}]`

@moalamri I tried your regex, but it didn't worked for me. Can you try it for yourself.

**Comment by androizer** [comment]
> Hey @androizer Could you try the following: `(class|className)=['{"]([^'"}]{10,120})['"}]`

I tried it and it worked. But I have to use number greater than 50 to make it work. 20 or 30 didn't worked for my case, which idk why.

**Comment by moalamri** [comment]
hey @androizer 
It is measured by characters not words, perhaps the shortest class value you have is 50 characters?

**Comment by moalamri** [comment]
> I would also like to see this properly configurable in the extension settings. Something like "Fold when there's a minimum of N classes".

This would make the extension work for a single purpose. It's useful in other use cases that's why I made it possible to tweak the regex 👍. It's also possible to configure minimum using the regex itself.
The most important feature I'm working on right now is to add support for language scoped settings which will make the extension more flexible

**Comment by androizer** [comment]
> hey @androizer It is measured by characters not words, perhaps the shortest class value you have is 50 characters?

It's working now. I think there may be some issue with the extension not loading correctly. You can add the characters threshold regex example in the readme so that others can find the solution easily.

You are free to close this thread. Once again, excellent work @moalamri. 👍

**Comment by moalamri** [comment]
@androizer 
I made some fixes in the recent two updates, please be sure to have the latest version.

You are right about documentation, it lacks some extra details. I will leave it to the contributors👍
