### ISSUE TITLE
Fold misplaced!

### ISSUE THREAD

**Issue by jsxclan** [moalamri/vscode-inline-fold#17]
Kindly fix this!

![image](https://user-images.githubusercontent.com/51025764/177739300-7b018d8d-3a47-4838-8d66-8803067144d6.jpeg)

**Comment by jsxclan** [comment]
> Does that happen with the default regex?

I think so because I haven't modified the extension settings tho.

**Comment by moalamri** [comment]
@jsxclan alright, thank you for reporting, I'll have a look soon 💭

**Comment by jsxclan** [comment]
Alright! Keep up the great work.

**Comment by moalamri** [comment]
Fixed

**Comment by moalamri** [comment]
A better solution is in the new version 0.1.4 
Please update and check the default regex 🙂
