### ISSUE TITLE
RegEx bug when selecting empty class/className

### ISSUE THREAD

**Issue by ccccooooddddyyyy** [moalamri/vscode-inline-fold#19]
Lines after an empty string class/className attribute `className=""`/`class=""` will be not folded.
![CleanShot 2022-07-08 at 18 54 42](https://user-images.githubusercontent.com/8092790/177987660-09fc0525-aa7f-41dd-9076-cc3f0605a8aa.png)
![CleanShot 2022-07-08 at 18 54 47](https://user-images.githubusercontent.com/8092790/177987664-719d5e62-125c-42b0-887c-bf9beefa238c.png)

**Comment by moalamri** [comment]
Good catch @ccccooooddddyyyy

**Comment by moalamri** [comment]
Fixed in 0.1.4

**Comment by ccccooooddddyyyy** [comment]
> Hi @ccccooooddddyyyy Could you please take a mini screenshot for the extension in action? Same as with the current screenshot. Because the current one has a typo and it looks obviously unreal to VS Code interface (I used carbon to generate it). Also you have a nice combination of colors 🙂
> 
> You are welcome to update the current one with a PR if you have time.
> 
> Thanks in advance

Happy to help! DM me on Twitter @ccccooooddddyyy for more discussion if needed.

<img width="1130" alt="CleanShot 2022-07-15 at 21 46 20@2x" src="https://user-images.githubusercontent.com/8092790/179247671-7326ceda-7875-4d37-a458-5b592476ffda.png">

**Comment by moalamri** [comment]
Hi @ccccooooddddyyyy 
That will do it :) 

thank you so much 😊
