### ISSUE TITLE
extension freeze the editor

### ISSUE THREAD

**Issue by ctf0** [moalamri/vscode-inline-fold#2]
first many thanks for this extension, it really helps.

i currently have a regex of `((?<=class=\").*?(?=\")|(?<=style=\").*?(?=\"))` which basically supports both **style & class**, 
however with files that are  200+ lines, it would cuz the whole thing to freeze, 

so is there a way to make this more performant ?

**Comment by moalamri** [comment]
Hi @ctf0 
I'm sorry for that, I tried to reproduce it, but VSCode didn't freeze in my side.
Anyways I believe it could happen since code refactoring is not done and it was a single day work.

So thanks for the heads up. I'll push an update with better performance since I believe it could be done better.

**Comment by ctf0** [comment]
worked like charm, thanks, i didnt notice that there was an option to decide the regex group, so thanks for that too.

**Comment by ctf0** [comment]
ps: if u can make the decoration styles configurable it would be awesome.

**Comment by moalamri** [comment]
> worked like charm, thanks, i didnt notice that there was an option to decide the regex group, so thanks for that too.

Good to hear that :) 
Still I'm optimizing the code to be more performant.

What do you mean by decoration styles?
Currently you can change any of the following settings to decorate the folding mask and folded content:

- `inlineFold.unfoldedOpacity` opacity of the unfolded code when is clicked by mouse or being selected
- `inlineFold.maskChar` text/character to mask "replace" the code when it is folded
- `inlineFold.maskColor` color of the mask character
- `inlineFold.after` an optional text/character to append to the end of folded code

**Comment by ctf0** [comment]
i meant padding and margins if possible.

**Comment by moalamri** [comment]
I'm afraid such decoration is (not available)[https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions].
Maybe in upcoming updates I will expose more options from the available decorations.
Regarding performance enhancing, I have pushed an update that decorate the visible portion of code only, so the performance will stay the same in all files sizes.

**Comment by ctf0** [comment]
oh ok, np then, thank you so much for your time and your help.
