### ISSUE TITLE
BUG: Folding Multiple Lines in JSX

### ISSUE THREAD

**Issue by adnanalbeda** [moalamri/vscode-inline-fold#22]
The extension is not capable of folding multiple lines in JSX className.

When it folds them, only the first line is fold. and when I click on the className, vscode render breaks, like the cursor hides for ever, and the selected line is not highlighted.

Example:

```jsx
export default function Sample(props: {active?: boolean}) {
  return <div className={classnames({
    "text-black bg-white": !props.active, 
    "text-white bg-black": props.active
    })}>
      Sample of the Bug
    </div>
}
```

The fold className look like this:

```jsx
export default function Sample(props: {active?: boolean}) {
  return <div className={*...*
    "text-white bg-black": props.active
    })}>
      Sample of the Bug
    </div>
}
```

**Comment by moalamri** [comment]
Hey @adnanalbeda 
For multiline folding use [Explicit Folding](https://github.com/zokugun/vscode-explicit-folding) extension.
