### ISSUE TITLE
Class names with the same letters as the attribute name will fold the attribute

### ISSUE THREAD

**Issue by desvandev** [moalamri/vscode-inline-fold#24]
![image](https://user-images.githubusercontent.com/8462871/179057393-3dd5a6e2-15a4-4460-adc1-becfbfc00172.png)
As you can see if you type "c" or "lass", etc, will break the attribute.

I know that this is hard to fix since this is not only used for ``class`` but maybe a fix could be to have 2 regex, one for the attribute and another for the value.

**Comment by desvandev** [comment]
I'm using the default regex. The attribute name is ``class``.
Basically I'm using the extension out of the box I just added a different replace string (the Tailwind logo)

**Comment by moalamri** [comment]
Hey @desvandev 
I'm unable to reproduce this :(
Are you using the latest version 0.1.5?

**Comment by desvandev** [comment]
I am using 0.1.5.
![Animation](https://user-images.githubusercontent.com/8462871/179100056-1a5d4d55-8f3d-4bfd-9a31-56f3b57ac1a2.gif)
![image](https://user-images.githubusercontent.com/8462871/179099744-2bc30ecc-f62c-47cb-b534-64c6ac9281b3.png)

**Comment by moalamri** [comment]
@desvandev 

Thank you so much for the effort.

I was able to reproduce it. Jee it's ugly 😅

**Comment by moalamri** [comment]
I need someone good with regex to help me figure this out 🤔

**Comment by JasperSurmont** [comment]
This is not because of some regex magic, it is because of the usage of indexOf:

```ts
// src/decorator.ts

// updateDecorations() {
   ...
   match[0].indexOf(matched) // --> if matched == 'class' and the attribute is also called 'class' it will take the index of the start
   ...
```

I proposed a solution in #25, although it is not the most beautiful.

**Comment by JasperSurmont** [comment]
So when I find some free time I can look into the possibility of processing the matching regex. In that case we simply: 
1. Get the regex group number that should be folded and find the starting index in the regex string
2. Put everything before this group in one big group: `(class|className)=[{'"]([^{'"]+)[}'"]` would become `((class|className)=[{'"])([^{'"]+)[}'"]`
3. We now always select group 2 for folding, and we know the index because it's the same length as the length of group 1.

If anything is wrong in this thought process please let me know :)

**Comment by moalamri** [comment]
@JasperSurmont 
Sounds good so far.
Here I made this simple repl to play with.
I don't know if you're experiencing the same, but when constantly restarting VS Code extension host while developing it always leak memory the send my PC to OOing. 🙂 

Create repl here:

**Comment by moalamri** [comment]
@JasperSurmont 
According do your suggestion, here's the best parsing method I could think of:
https://replit.com/@moalamri/Regex-anatomy?v=1

**Comment by JasperSurmont** [comment]
Aha smart, check the last character to check where folding should start :).
You should indeed put in the readme then that the folding group should be inside 2 delimiters, but I think almost all use cases of this plugin are like that

**Comment by moalamri** [comment]
@JasperSurmont 👍🏻 Correct :)
Don't you worry about the group or regex validation as if the regex isn't applicable it will fail to apply any decoration 💯 
Please check your PR, I applied your suggestion there.
If all good then I can merge it :D
