### ISSUE TITLE
Add a keyboard shortcut to show and hide all of the classes

### ISSUE THREAD

**Issue by babakfp** [moalamri/vscode-inline-fold#29]
- It will affect the whole document, not just the file that you used the shortcut.
- A shortcut that you can easily use with 1 hand.
- We can also have a config option to set is the classes going to be visible or hidden by default.

**Comment by babakfp** [comment]
> What do you mean by 1 hand?

Being able to press the shortcut keys without needing your right/second hand.

> Could you explain more?

Nevermind

**Comment by JasperSurmont** [comment]
For me doing the `Toggle Inline Fold` is already applied to the entire workspace, and not to the current file.

Shortcuts are customizable in VSCode itself, extensions have nothing to do with them really (apart for setting default values I think). To do so, follow these steps:

1. `Ctrl` + `Shift` + `p`
2. Type `Open keyboard shortcuts` and select it (not the JSON one)
![image](https://user-images.githubusercontent.com/28810440/180068037-088bdb69-9a45-4919-8567-c0af0cf86c26.png)
3. Type in the search bar `inlineFold.toggle`
![image](https://user-images.githubusercontent.com/28810440/180068174-ba6b67b5-16a3-46f4-937b-cb1c9c296d4a.png)
4. Assign a keyboard shortcut by double clicking the row

**Comment by moalamri** [comment]
> Being able to press the shortcut keys without needing your right/second hand.

Of course you can go to VS Code keyboard shortcuts settings, search for the extension's command name `inline fold` then bind any keyboard shortcut you want, even if a single letter :)


> Nevermind 
> 
It could sound like a great idea, so share when you want.

**Comment by moalamri** [comment]
> For me doing the `Toggle Inline Fold` is already applied to the entire workspace, and not to the current file.
> 
> 
> 
> Shortcuts are customizable in VSCode itself, extensions have nothing to do with them really (apart for setting default values I think). To do so, follow these steps:
> 
> 
> 
> 1. `Ctrl` + `Shift` + `p`
> 
> 2. Type `Open keyboard shortcuts` and select it (not the JSON one)
> 
> ![image](https://user-images.githubusercontent.com/28810440/180068037-088bdb69-9a45-4919-8567-c0af0cf86c26.png)
> 
> 3. Type in the search bar `inlineFold.toggle`
> 
> ![image](https://user-images.githubusercontent.com/28810440/180068174-ba6b67b5-16a3-46f4-937b-cb1c9c296d4a.png)
> 
> 4. Assign a keyboard shortcut by double clicking the row

Should we call it a feature or a bug 🤷?

**Comment by JasperSurmont** [comment]
> 
> Should we call it a feature or a bug 🤷?
> 

I think it's better this way :)
