### ISSUE TITLE
Support for Nunjucks

### ISSUE THREAD

**Issue by pexeixv** [moalamri/vscode-inline-fold#33]
I use [Eleventy.js](https://11ty.dev), which uses [Nunjucks](https://mozilla.github.io/nunjucks/) as templating engine.

**Comment by moalamri** [comment]
Hey @pexeixv.
I have never heard of Nunjuncks but it seems to be compile-able so it's just the regex that you need to change.
If you give me an example from the template of what you trying to mask I could provide you a regex and its group.

**Comment by pexeixv** [comment]
It normally starts with YAML frontmatter, defined between a pair of 3 hyphens, followed by the HTML. YAML frontmatter is optional.
For example
```njk
---
title: Home
layout: base.njk
---

<link rel="stylesheet" href="/styles/aos@2.3.1.css">
<section class="bg-black text-white" style="background: black url('/img/banner-trans.png') top left no-repeat;">
    <main class="container mx-auto flex flex-col items-start lg:items-center gap-5 px-5 py-28 lg:py-40 lg:text-center">
        <h1 class="text-4xl md:text-5xl lg:text-7xl font-black tracking-tight drop-shadow" data-aos="fade-up">
            AHK scripts and
            <br class="hidden md:block">
            videos uploaded all the
            <br class="hidden md:block">
            time just for you!
        </h1>
        <p class="text-gray-300 text-lg lg:text-xl w-3/4 lg:w-full" data-aos="fade-up" data-aos-delay="400">
            Email us your script to showcase on the site or in a video!
        </p>
        <div data-aos="fade-up" data-aos-delay="800" class="flex gap-5 items-center">
            {% set props = { link: "mailto:testmail@gmail.com?subject=Tab%20Nations%20Code", text: "Mail to us"} %}
            {% include 'button.njk' %}
            {% set props = { link: "http://youtube.com/user/testchannel?sub_confirmation=1", text: "Check out videos"} %}
            {% include 'button.njk' %}
        </div>
    </main>
</section>

```

**Comment by moalamri** [comment]
This is not the compiled or pre-compiled output?
If this is what you see in the IDE, you could simply make the extension work out-of-the-box.
You only need to add the language id to the extension's supported languages settings.
The question is what is the language id of Nunjucks. I googled and got the following, I will post the full settings here, let me know if that fixes the language support: 

```
"inlineFold.supportedLanguages": [
"nunjucks",
"nunj",
"njs"
]
```
