### ISSUE TITLE
Suggestion to rethink the extension's functionality

### ISSUE THREAD

**Issue by abubakarutar** [moalamri/vscode-inline-fold#35]
This extension is amazing when working with Tailwindcss. I think it will be more functional if you could have a toggle to activate the inline fold, instead of the extension automatically inline folding when you aren't editing the className. Functionality like multi-cursor editing is completely unusable with the way the extension works now.

Thank you.

**Comment by moalamri** [comment]
The extension already has a toggle command.
It also unfold when multi-cursor is used.
What version are you using?
