### ISSUE TITLE
Support Template Literals

### ISSUE THREAD

**Issue by cnguyen-de** [moalamri/vscode-inline-fold#39]
Hi, I've encounter a bug in Vue application: 

Actual code:
![Screenshot 2022-08-06 at 12 14 04](https://user-images.githubusercontent.com/6671583/183244696-0ad2497a-ff49-4b96-bcdc-136a43b3b149.png)

What it is showing:
![Screenshot 2022-08-06 at 12 13 35](https://user-images.githubusercontent.com/6671583/183244686-7ca23d9d-e85f-4887-b8ec-9638be7ee588.png)

Expectation: 
1. whole object inside :class is hidden
OR
2. nothing is hidden at all

**Comment by moalamri** [comment]
Hi,
Does this happen when the class value is in the same line?

**Comment by cnguyen-de** [comment]
Sorry for the late reply, also happens in the same line: 

<img width="312" alt="Screenshot 2022-08-09 at 12 46 31" src="https://user-images.githubusercontent.com/6671583/183629883-d868c11b-bfd7-4f75-9bdf-496561bb2519.png">

**Comment by moalamri** [comment]
Hi,
I see what you mean, it is a known issue I should have mentioned it on the home page.
You're using what is called template literal which could have any character from the default regex (the part that matches the ending delimiter).
There are two solutions, I either use a react/vue parser (transpiler) which I will have to import the whole react&react-dom which i don't plan to do. Or write a method that manually matches things by guessing the correct end character by a balanced pair.

Once I find time, I will work on the second option. :)

**Comment by e-medeiros** [comment]
@cnguyen-de if you decrease version to 0.1.5 you can use my regex... it fits your case.
using this version until 0.2.0 comes and solve some things.
```(class)\s*=\s*)((["'])|{`)((?!\3)(\n.|.)+?)((\3)(?!{`)|`})``` - group 5

tried so find some regex for substrings of a pattern but find nothing. be aware of  #24...

**Comment by moalamri** [comment]
@e-medeiros I've looked into how tailwindcss compile values and they are using the same method I mentioned that I'm going to implement in next version which goes by guessing the end delimiter with a balanced pair, the developer added a comment saying "this is a naive way", so it could be the only method beside implementing AST for react and vue

**Comment by moalamri** [comment]
I've moved this to [#46](https://github.com/moalamri/vscode-inline-fold/issues/46)
