### ISSUE TITLE
Support for React/Typescript React

### ISSUE THREAD

**Issue by ccccooooddddyyyy** [moalamri/vscode-inline-fold#4]
```json
"inlineFold.supportedLanguages": [
  "html",
  "svelte",
  "react",
  "javascript react",
  "typescript react",
  "javascript",
  "js",
  "tsx",
  "jsx",
  "ts"
],,
"inlineFold.regex": "className=\".+?(?=\")",
```

These are settings I've tried to achieve `className` folding in .tsx files.

I'm not sure it is not supported yet or I haven't do it right.

**Comment by moalamri** [comment]
Hey @ccccooooddddyyyy 
This should work with reactjs

https://regex101.com/r/8Jj6Q9/1

Make sure you set "inlineFold.regexGroup": 2

**Comment by ccccooooddddyyyy** [comment]
> Hey @ccccooooddddyyyy This should work with reactjs
> 
> https://regex101.com/r/8Jj6Q9/1
> 
> Make sure you set "inlineFold.regexGroup": 2

Thanks for replying.

Here's screenshot of my settings. It's still not work tho :D
![CleanShot 2022-07-04 at 01 36 23](https://user-images.githubusercontent.com/8092790/177052878-ab0701d3-f858-4987-bee9-c068dab4228a.png)

**Comment by moalamri** [comment]
When you open .tsx file what is the file language is displayed in the right side of the status bar?

![image](https://user-images.githubusercontent.com/964077/177053983-741c3c10-b200-4de8-8c45-e43542ed5632.jpeg)

**Comment by ccccooooddddyyyy** [comment]
> When you open .tsx file what is the file language displayed in the right side of the status bar?
> 
> ![image](https://user-images.githubusercontent.com/964077/177053983-741c3c10-b200-4de8-8c45-e43542ed5632.jpeg)
> 
> Also could you show me the code you trying to fold

It's Typescript React.
![CleanShot 2022-07-04 at 02 18 30](https://user-images.githubusercontent.com/8092790/177054198-d56da954-a536-4fc6-9b2e-bf6b471655c4.png)

**Comment by moalamri** [comment]
Add `typescriptreact` to the languages list.

The extension uses `languageId` as because a language could have more than one file extension & aliases

Here's a list of known languages 
[Known language identifiers](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers)

**Comment by ccccooooddddyyyy** [comment]
> Add `typescriptreact` to the languages list.
> 
> The extension uses `languageId` as because a language could have more than one file extension & aliases
> 
> Here's a list of known languages [Known language identifiers](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers)

Worked perfectly! I wished to find information like this in the docs even nicer if it comes with regex settings.

**Comment by moalamri** [comment]
> 
> Worked perfectly! I wished to find information like this in the docs even nicer if it comes with regex settings.
> 

Good to hear that :)
Sure I'll update the docs with some common regex examples also more descriptive settings.

> One more question before this will be closed, how can i use regex to select `` ` `` (backtick) or `{` (open curly bracket) after `className` ![CleanShot 2022-07-04 at 04 08 52](https://user-images.githubusercontent.com/8092790/177057338-c0ca51e1-583b-48a3-ac94-ba44debe0adc.png)

That's why I asked for the code because the regex I gave worked only for double quotes className. Try this https://regex101.com/r/RkCWEk/1 and if you mean `{` and `` ` `` could come together? I'm not really familiar with reactjs, but if so then I guess it's also achievable https://regex101.com/r/NuDLoF/1
Both use the default group number: 2

**Comment by dougwithseismic** [comment]
![image](https://user-images.githubusercontent.com/48530756/177107560-0765e6e7-1464-4442-93c9-2414c593270d.png)

For anyone wanting to get set up quickly with React.

1. Ctrl + Shift + P -> Open Settings (JSON)
2. Add the below 

```json
"inlineFold.regex": "(className)=[{`'\"]([^\\'`\"}]*)[\"'`}]",
"inlineFold.supportedLanguages": [
    "html",
    "svelte",
    "javascriptreact",
    "jsx",
    "typescriptreact",
    "javascript"
],
"inlineFold.regexGroup": "2"
```

**Comment by moalamri** [comment]
@dougwithseismic 
Thank you so much.
I'll push an update soon that has even better performance and eliminate the unnecessary events triggers.

Anyways I will mention you when I'm done so that if you cloud have free time you could help with docs 😊

**Comment by moalamri** [comment]
Please update the extension and restart VS Code then reset the `regex` and `regexGroup` settings to the default values.
