### ISSUE TITLE
support tailwind-merge 

### ISSUE THREAD

**Issue by DanielDerma** [moalamri/vscode-inline-fold#56]
Should fold inside of the parenthesis, not the 'twMerge', that would be perfect.

**Comment by e-medeiros** [comment]
@DanielDerma could you provide your configurantion and a exemple code ?

**Comment by DanielDerma** [comment]
> @DanielDerma could you provide your configurantion and a exemple code ?

(project example that use **twMerge** from **'tailwind-merge'** with flesh vscode setup on codespace(this also happens on my workspace) 

This is how looks with 'Inline fold' extension enable:
![image](https://user-images.githubusercontent.com/37880797/190065866-a7b21752-d236-4016-90df-caebcb06666b.png)

And this is how looks when i disabled:
![image](https://user-images.githubusercontent.com/37880797/190065980-72ef8672-dae9-49b2-9c79-579a4ac0acf9.png)

**Comment by moalamri** [comment]
@DanielDerma You don't want `twMerge` to be folded with the rest of the folded content? if so then you can tweak the regex to have `twMerge` in the pre fold captured group which has `class` and `className` . Or simply use `(^twMerge)` so it doesn't get matched with the folded group.
