### ISSUE TITLE
Extension shouldn't attempt to fold :class properties in Vue files

### ISSUE THREAD

**Issue by wc-davide** [moalamri/vscode-inline-fold#57]
With the following code:
![image](https://user-images.githubusercontent.com/46521712/191019777-afa3e9ed-1332-46b8-97c6-8f4f91b8d862.png)

The extension attempts to fold the `:classes`, resulting in a broken code indentation:
![image](https://user-images.githubusercontent.com/46521712/191019742-8c813036-dc58-497b-ba09-a8bad54c3db7.png)

This can currently be fixed by changing the setting `inlineFold.regex` to:
```regex
(class|className)=[`'{"]([^`'"{}]+)[`'"}]
```
(added a `{` in the middle part)

Maybe a better solution could be something like this:
```(class|className)=([`'"{])([^]+?)\2```
but you will probably need to update the capture groups indexes in the code

**Comment by moalamri** [comment]
Hi @wc-davide
You can change the capture group number with `inlineFold.regexGroup`.
Also, I think it will be easier to just add a space or tab character in the regex like [this example](https://regex101.com/r/5KycQx/1)
I'm not sure if vuejs can have any custom directives pre `class`, but if so, then yes, I think it's the perfect solution.
What do you think?

**Comment by wc-davide** [comment]
> Hi @wc-davide You can change the capture group number with `inlineFold.regexGroup`. Also, I think it will be easier to just add whitespace character in the regex like [this example](https://regex101.com/r/NAp5vw/1) I'm not sure if vuejs can have any custom directives pre `class`, but if so, then yes, I think it's the perfect solution. What do you think?

I tried changing the regexGroup but the regex ```(class|className)=([`'"{])([^]+?)\2``` still doesn't seem to work.
Either way I realized there's an issue with that, cause the "ending quote" isn't always the same as the "starting quote", example: `class={ ... }` (I don't know what language this is, react maybe?).

So maybe the whitespace is the best solution?

---

My colleague sent me this: https://regex101.com/r/RkbPp9/1
Which could be a solution, but it would need code update to handle the changing capturing group (group 3 normally, group 4 when `{}` are used)

**Comment by wc-davide** [comment]
> Since you use normal values in the class and far from using jsx. I think you can simply remove the jsx containers `{}` and use a whitespace. 👍

Yes, I found a solution for myself. I made this issue hoping to find a global solution that would for everyone... but as you said in the UPDATE it's not that easy unfortunately...

**Comment by moalamri** [comment]
I'm glad you sorted it out :)
Maybe in upcoming update I will make the default regex with pre whitespace 👍🏻 

Feel free to reopen if you have a suggestion.
