### ISSUE TITLE
a simple / documented way to fold only after N numer of characters

### ISSUE THREAD

**Issue by dJani97** [moalamri/vscode-inline-fold#60]
Hi!

Sometimes I have only a couple of short classnames which I don't necessarily want to fold, so I modified the regex to only fold a list of classes if it's longer than 30 characters:

```
(class|className)=[`'{"]([^`'"}]{30,})[`'"}]
```

I feel like this example could be added to the docs as it seems like a common use-case to me.

**Comment by moalamri** [comment]
Hi @dJani97 
That's an interesting use case :)
If you have found it working and are interested in documenting that, then branch dev/v0.1.8 is for the upcoming update which will be released very soon, I have added a section of examples for use cases if you want to add PR 👍🏻
