### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by onattech** [moalamri/vscode-inline-fold#65]
Assalamu alaykum Mohammad,

Great work with the extension, may Allah reward you. I am trying get it to work with Material UI sx property. It works fine if all the properties are on the same line but if the line is long enough, prettier formats it to be multiline and that breaks your extension. Here's what I got so far.
Here's my config regex
`(class|className|sx)=(({?{(`|))|(['"`]))((.|\n)*?)(}?})`

Here's the code uncollapsed
![image](https://user-images.githubusercontent.com/53895969/195984927-de440d68-b296-4501-880a-c1da32aa6925.png)

Here's the code collapsed
![image](https://user-images.githubusercontent.com/53895969/195984935-12c646f4-1589-47a2-b6ec-0d79855c710f.png)

Ideally, I would like to have two closing curly brackets on line 161 instead of line 167 and collapse what is in between. Any way to achieve this?

**Comment by moalamri** [comment]
Alaykom Alsalam @onattech .
Thank you so much 😃 

If the linter is forcing your code to expand in multilines, then there's nothing the extension can do, but there are other methods to make the code fold like using [fold selection](https://code.visualstudio.com/updates/v1_70#_fold-selection) or using [this extension](https://marketplace.visualstudio.com/items?itemName=zokugun.explicit-folding) that make real folding (unlike my extension) to multiline content.

**Comment by onattech** [comment]
Will look into those. Thank you. 👍🏼
