### ISSUE TITLE
Language scoped settings

### ISSUE THREAD

**Issue by ARogueOtaku** [moalamri/vscode-inline-fold#7]
Hi,

First off, thanks for developing this extension. This helps a lot when working with large texts.

Would be awesome if the regex config was an array instead of just a single string. This will enable users to declare multiple formats instead of trying to fit everything in single regex.

An even more ambitious ask would be to declare profiles. Where each profile will contain the regex it will match and the mask character , supported languages etc. But I understand that might be too resource consuming.

**Comment by moalamri** [comment]
Hey @ARogueOtaku 

The better way to do that is to use language scoped settings.
For example

```json
['svelte']: {
Regex and other settings
}
```

In that way only specific regex will be used according to the scoped language and you can have multiple regex without affecting any performance.

I will look into that and see what I can do.

**Comment by ARogueOtaku** [comment]
Hey, @moalamri yup, so instead of creating a profile, you a proposing each language is a regex profile itself. Yes I like that. That would be great. Thanks

**Comment by moalamri** [comment]
@ARogueOtaku 
Exactly. It will be language scoped instead of manually adding supported languages in the top level.
Also would allow to have different settings for each language.
