### ISSUE TITLE
Astro support

### ISSUE THREAD

**Issue by monstajoe2002** [moalamri/vscode-inline-fold#72]
This plugin doesn't fold tailwind boilerplate classes in ```.astro``` files like ```.html``` or ```.jsx```

**Comment by moalamri** [comment]
I couldn't find it in here either https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers

What is the language mode of the editor when you open an `.astro` file?
You can find it in the bottom right of the editor
<img width="135" alt="image" src="https://user-images.githubusercontent.com/964077/202926641-572d2156-c670-4926-9db4-d024000947ec.png">

**Comment by monstajoe2002** [comment]
Astro
