### ISSUE TITLE
fold rest of class names but not the first one

### ISSUE THREAD

**Issue by laricoDGT** [moalamri/vscode-inline-fold#73]
It's possible to fold all but no the first one, to get a reference what is the basic class name for identify to naked eye.

**example:**

from:
`<div class="...">`

to:
`<div class="general ...">`

on this case, i can see my "general" class name then folded...

by default all is folded, so, i can't indentify unless you click the class or selector.

**Comment by moalamri** [comment]
Yes, there's an example at the home page for when you want to fold after set of characters.
Also it's easier if you use the registered commands to fold/unfold

feel free to reopen issue if needed 👍🏻
