### ISSUE TITLE
Support for classnames / clsx packages

### ISSUE THREAD

**Issue by liel-almog** [moalamri/vscode-inline-fold#77]
Is it possible to add support for classnames and clsx packages from npm.
I mostly use this extension for React projects and I often use these package.
I tried to find the right regex to suggest a PR but unfortunately I could do very little.

Thank you!

![image](https://user-images.githubusercontent.com/70017134/208179435-38b60f74-b13f-4a31-bce0-733b69ccfc4b.png)

**Comment by moalamri** [comment]
Hi @liel-almog 
Sorry for late. 
I guess you are trying to fold multiline? because I don't really know what you mean by `classnames and clsx packages from npm` . if you could mark a place at the screenshot of which part you want to fold?

**Comment by liel-almog** [comment]
I really think this is more about multi-line folding because I have times when applying styles dynamically using variable and my formatter expends it across multiple lines

**Comment by moalamri** [comment]
hey @liel-almog 
As I have explained here https://github.com/moalamri/vscode-inline-fold/discussions/69#discussioncomment-4150206
It is not possible at the moment :(

Feel free to re-open if needed 👍🏻
