### ISSUE TITLE
does not work, cannot find any instruction\command\shortcut

### ISSUE THREAD

**Issue by jt6677** [moalamri/vscode-inline-fold#78]
what do I suppose to do to get it to work? Do I hit a shortcut or type in a command in ctrl+p? Do I highlight the code I wan to fold?

**Comment by jt6677** [comment]
I installed v0.1.10 and it jumped to v0.0.5. very odd.

**Comment by moalamri** [comment]
Hey @jt6677 
What is the VSCode version you're using? Perhaps it doesn't support the VSCode engine used in the extension, which is the latest version.

**Comment by jt6677** [comment]
> 

that fixed it.  Thank you.

**Comment by jt6677** [comment]
I have tried for longer than 40 mins to get className={cn(xxxxx)} to fold. Anyone has the correct regex to fold this? Thank you

**Comment by moalamri** [comment]
@jt6677 there’s an example at the main page for your use case

feel free to reopen if needed
