### ISSUE TITLE
Publish to Open VSX Registry

### ISSUE THREAD

**Issue by hzmmohamed** [moalamri/vscode-inline-fold#85]
Greetings,
Thank you for this awesome extension! I suggest that it's also published to [Open VSX Registry](https://open-vsx.org) so that VSCodium users can easily find and download it.

**Comment by RickRyan26** [comment]
Came here to say the exact same thing so that I can use it in GitPod lol

**Comment by moalamri** [comment]
I have published it https://open-vsx.org/extension/moalamri/inline-fold, but not yet verified and I have opened a [namespace claim](https://github.com/EclipseFdn/open-vsx.org/issues/1565) request.
I'm not sure if you will be able to download it yet or not.

**Comment by moalamri** [comment]
Done

**Comment by hzmmohamed** [comment]
Thanks a lot! @moalamri
