### ISSUE TITLE
Multi-line folding

### ISSUE THREAD

**Issue by axelrindle** [moalamri/vscode-inline-fold#93]
Imagine the following code snippet:

```jsx
<button
	className={`
		w-10 h-10 text-primary cursor-pointer
		border-primary border-2 rounded-full
		flex items-center justify-center
		transition-colors
		enabled:hover:bg-primary hover:text-white
		enabled:active:bg-violet-900 active:text-white
		disabled:cursor-not-allowed disabled:border-gray-300 disabled:text-gray-300
	`}
>
```

That might be considered quite ugly, I know :)

I'd like to request support multi-line folding for cases similar to the one above. I already tried modifying the regex flags to be `gs` but that just left the lines being empty instead of truly folded.

Is that something you'd consider implementing?

**Comment by e-medeiros** [comment]
@axelrindle this topic is already replied in #69.
