### ISSUE TITLE
Regex replacing only "style"

### ISSUE THREAD

**Issue by JustPCode** [moalamri/vscode-inline-fold#96]
Hi, i just found out this extension and it's exactly what i needed but, on a markdown file, when i try to minimize styling options (`<span style="color: red">a</span>`) with this RegEx `(class|className|style)=(({(`|))|(['"`]))(.*?)(\2|(\4)}|"*")` it covers only "style"
![Code_wGIFLTo0VE](https://user-images.githubusercontent.com/64895799/215282555-bb7d4757-b71e-4bea-afcf-6bdcdfff7a7e.png)

Here there are the other options
![Code_H2TXfqKaOF](https://user-images.githubusercontent.com/64895799/215282593-23cc3013-3cff-441e-935f-f49dd1c819d0.png)

I don't use RegEx often but even on regex101 it says that it should work:
![yQm2L4I112](https://user-images.githubusercontent.com/64895799/215282682-aaa7f9aa-a29d-44e9-8d7e-e160967d5dc2.png)

please, could you help me

**Comment by moalamri** [comment]
Hey @JustPCode 
If it is only the style attribute that you want to match then this regex could definitely do the job `style="([^"]*)"` set capture group to `1` and flags could me `g`

**Comment by moalamri** [comment]
I'm not sure if this issue still exist or not 🤔

**Comment by JustPCode** [comment]
let me show you

if I type `style=(".*")` it collapse everything between the `" "` even if the group is setted to two

![firefox_jYaZ1NdLGo](https://user-images.githubusercontent.com/64895799/215310041-0982deb2-fedd-429a-bd64-327e5ebbd6e1.png)

Let's try another example, the default one (`(class|className|style)=(({(|))|(['"]))(.*?)(\2|(\4)}|"*")`), even changing the group it still collapses "style" (aka. group 1)
![image](https://user-images.githubusercontent.com/64895799/215310178-c0431630-52d7-48ff-bf47-8ddea652bfda.png)
![Code_E67cDSSVsr](https://user-images.githubusercontent.com/64895799/215310200-fc25ad2b-8577-47b0-9eb9-c3e663570119.png)

**Comment by JustPCode** [comment]
I'm stupid, i had settings overwritten by project ones, I'm truly sorry for wasting your time and wish you a good day

**Comment by moalamri** [comment]
@JustPCode it's ok, happens to the best of us 😅
